"use client";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { useState, type ReactNode } from "react";

const nav = [["/dashboard","▦","Overview"],["/users","◎","Users"],["/requests","◫","Buyer requests"],["/offers","◇","Offers & deals"],["/reports","△","Reports"],["/billing","$","Billing"],["/settings","⚙","Settings"]];
export function AdminShell({ children }: { children: ReactNode }) {
  const path = usePathname();
  const [navigationOpen, setNavigationOpen] = useState(false);
  return <div className={`shell ${navigationOpen ? "navigation-open" : ""}`}><button className="nav-backdrop" aria-label="Close navigation" onClick={()=>setNavigationOpen(false)}/><aside className="sidebar"><div className="brand"><span className="brandmark">H</span><div><strong>Hocalist</strong><small>Admin portal</small></div><button className="nav-close" aria-label="Close navigation" onClick={()=>setNavigationOpen(false)}>×</button></div><div className="demo-rail">Phase 1 · Demo workspace</div><nav>{nav.map(([href,icon,label])=><Link key={href} href={href} className={path===href?"active":""} onClick={()=>setNavigationOpen(false)}><span>{icon}</span>{label}</Link>)}</nav><div className="side-footer"><Link href="/login">↗ Sign out preview</Link><small>Mock data only<br/>No live actions</small></div></aside><main className="workspace"><header className="topbar"><button className="menu" aria-label="Open navigation" aria-expanded={navigationOpen} onClick={()=>setNavigationOpen(true)}>☰</button><label className="global-search"><span>⌕</span><input aria-label="Global search" placeholder="Search demo records"/><kbd>⌘ K</kbd></label><div className="admin-id"><span className="alert-dot">3</span><div><strong>Alex Rivera</strong><small>System administrator</small></div><span className="avatar">AR</span></div></header><div className="canvas">{children}</div></main></div>;
}
export function PageHeader({ title, description, action }: { title:string; description:string; action?:string }) { return <div className="page-head"><div><p className="eyebrow">Operations console</p><h1>{title}</h1><p>{description}</p></div>{action&&<button className="primary">＋ {action}</button>}</div>; }
export function DemoNotice() { return <div className="demo-notice"><strong>Demo data</strong><span>This Phase 1 dashboard is a visual prototype. Filters and actions do not change live records.</span></div>; }
export function Stat({label,value,note,tone="blue"}:{label:string;value:string;note:string;tone?:string}) { return <article className={`stat ${tone}`}><span className="stat-icon">{tone==="red"?"!":tone==="gold"?"◇":"↗"}</span><p>{label}</p><strong>{value}</strong><small>{note}</small></article>; }
export function Status({children}:{children:ReactNode}) { const value=String(children).toLowerCase(); const tone=value.match(/active|verified|selected|resolved|matched/) ? "success" : value.match(/critical|restricted|past due/) ? "danger" : value.match(/review|trial|open|high|escalated/) ? "warning" : value.match(/new|shortlisted/) ? "info" : "neutral"; return <span className={`status ${tone}`}>{children}</span>; }
export function Filters({placeholder="Search records", options=["All statuses"]}:{placeholder?:string;options?:string[]}) { return <div className="filters"><label><span>⌕</span><input placeholder={placeholder}/></label>{options.map(x=><select aria-label={x} key={x}><option>{x}</option><option>Active</option><option>Needs review</option><option>Closed</option></select>)}<button>↧ Export</button></div>; }
export function DataTable({columns,rows,statusIndex=3,emptyTitle="No matching records"}:{columns:string[];rows:string[][];statusIndex?:number;emptyTitle?:string}) { return <div className="table-card"><div className="table-scroll"><table><thead><tr>{columns.map(c=><th key={c}>{c}</th>)}<th><span className="sr-only">Actions</span></th></tr></thead><tbody>{rows.length?rows.map((r,i)=><tr key={i}>{r.map((c,j)=><td key={j}>{j===0?<strong>{c}</strong>:j===statusIndex?<Status>{c}</Status>:c}</td>)}<td><button className="row-action" aria-label={`Open ${r[0]}`}>•••</button></td></tr>):<tr><td colSpan={columns.length+1}><EmptyState title={emptyTitle}/></td></tr>}</tbody></table></div><footer className="pagination"><span>Showing {rows.length} demo records</span><div><button disabled>‹</button><button className="current">1</button><button>2</button><button>›</button></div></footer></div>; }
export function EmptyState({title}:{title:string}) { return <div className="empty"><span>⌕</span><strong>{title}</strong><p>Try adjusting the demo filters or search phrase.</p></div>; }
export function Section({title,children,link}:{title:string;children:ReactNode;link?:string}) { return <section className="section"><div className="section-title"><h2>{title}</h2>{link&&<Link href={link}>View all →</Link>}</div>{children}</section>; }
